<?php

return [
	'post_type' => 'post-type-name',
	'args'      => [
		'label'               => __( '<replace>', 'swpt' ),
		'labels'              => [
			'name'                  => __( '<replace>', 'swpt' ),
			'singular_name'         => __( '<replace>', 'swpt' ),
			'add_new'               => __( 'Add <replace>', 'swpt' ),
			'add_new_item'          => __( 'Add new <replace>', 'swpt' ),
			'edit_item'             => __( 'Edit <replace>', 'swpt' ),
			'new_item'              => __( 'New <replace>', 'swpt' ),
			'view_item'             => __( 'View <replace>', 'swpt' ),
			'search_items'          => __( 'Search <replace>s', 'swpt' ),
			'not_found'             => __( '<replace>s not found', 'swpt' ),
			'not_found_in_trash'    => __( '<replace>s not found in trash', 'swpt' ),
			'parent_item_colon'     => __( 'Parent <replace>:', 'swpt' ),
			'menu_name'             => __( '<replace>s', 'swpt' ),
			'all_items'             => __( 'All <replace>s', 'swpt' ),
			'archives'              => __( '<replace> archives', 'swpt' ),
			'insert_into_item'      => __( 'Insert into <replace>', 'swpt' ),
			'uploaded_to_this_item' => __( 'Uploaded to this <replace>', 'swpt' ),
			'featured_image'        => __( '<replace> Featured image', 'swpt' ),
			'set_featured_image'    => __( 'Set <replace> Featured image', 'swpt' ),
			'remove_featured_image' => __( 'Remove <replace> Featured image', 'swpt' ),
			'use_featured_image'    => __( 'Use <replace> Featured image', 'swpt' ),
			'filter_items_list'     => __( 'Filter <replace>s list', 'swpt' ),
			'items_list_navigation' => __( '<replace>s list navigation', 'swpt' ),
			'items_list'            => __( '<replace>s list', 'swpt' ),
			'name_admin_bar'        => __( '<replace>', 'swpt' ),
			'view_items'            => __( 'View <replace>s', 'swpt' ),
			'attributes'            => __( 'Attributes', 'swpt' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => '',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
//		'supports'            => [ 'title' ],
		'taxonomies'          => [],
		'has_archive'         => true,
//		'rewrite'             => [
//			'slug' => 'slug',
//		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
