<?php

return [
	'post_type' => 'group',
	'args'      => [
		'label'               => __( 'Group', 'school' ),
		'labels'              => [
			'name'                  => __( 'Group', 'school' ),
			'singular_name'         => __( 'Group', 'school' ),
			'add_new'               => __( 'Add Group', 'school' ),
			'add_new_item'          => __( 'Add new Group', 'school' ),
			'edit_item'             => __( 'Edit Group', 'school' ),
			'new_item'              => __( 'New Group', 'school' ),
			'view_item'             => __( 'View Group', 'school' ),
			'search_items'          => __( 'Search Groups', 'school' ),
			'not_found'             => __( 'Groups not found', 'school' ),
			'not_found_in_trash'    => __( 'Groups not found in trash', 'school' ),
			'parent_item_colon'     => __( 'Parent Group:', 'school' ),
			'menu_name'             => __( 'Groups', 'school' ),
			'all_items'             => __( 'All Groups', 'school' ),
			'archives'              => __( 'Group archives', 'school' ),
			'insert_into_item'      => __( 'Insert into Group', 'school' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Group', 'school' ),
			'featured_image'        => __( 'Group Featured image', 'school' ),
			'set_featured_image'    => __( 'Set Group Featured image', 'school' ),
			'remove_featured_image' => __( 'Remove Group Featured image', 'school' ),
			'use_featured_image'    => __( 'Use Group Featured image', 'school' ),
			'filter_items_list'     => __( 'Filter Groups list', 'school' ),
			'items_list_navigation' => __( 'Groups list navigation', 'school' ),
			'items_list'            => __( 'Groups list', 'school' ),
			'name_admin_bar'        => __( 'Group', 'school' ),
			'view_items'            => __( 'View Groups', 'school' ),
			'attributes'            => __( 'Attributes', 'school' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-groups',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'supports'            => [ 'title' ],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => [
			'slug' => 'groups',
		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
