<?php

return [
	'post_type' => 'question',
	'args'      => [
		'label'               => __( 'Question', 'school' ),
		'labels'              => [
			'name'                  => __( 'Question', 'school' ),
			'singular_name'         => __( 'Question', 'school' ),
			'add_new'               => __( 'Add Question', 'school' ),
			'add_new_item'          => __( 'Add new Question', 'school' ),
			'edit_item'             => __( 'Edit Question', 'school' ),
			'new_item'              => __( 'New Question', 'school' ),
			'view_item'             => __( 'View Question', 'school' ),
			'search_items'          => __( 'Search Questions', 'school' ),
			'not_found'             => __( 'Questions not found', 'school' ),
			'not_found_in_trash'    => __( 'Questions not found in trash', 'school' ),
			'parent_item_colon'     => __( 'Parent Question:', 'school' ),
			'menu_name'             => __( 'Questions', 'school' ),
			'all_items'             => __( 'All Questions', 'school' ),
			'archives'              => __( 'Question archives', 'school' ),
			'insert_into_item'      => __( 'Insert into Question', 'school' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Question', 'school' ),
			'featured_image'        => __( 'Question Featured image', 'school' ),
			'set_featured_image'    => __( 'Set Question Featured image', 'school' ),
			'remove_featured_image' => __( 'Remove Question Featured image', 'school' ),
			'use_featured_image'    => __( 'Use Question Featured image', 'school' ),
			'filter_items_list'     => __( 'Filter Questions list', 'school' ),
			'items_list_navigation' => __( 'Questions list navigation', 'school' ),
			'items_list'            => __( 'Questions list', 'school' ),
			'name_admin_bar'        => __( 'Question', 'school' ),
			'view_items'            => __( 'View Questions', 'school' ),
			'attributes'            => __( 'Attributes', 'school' ),
		],
		'description'         => '',
		'public'              => false,
		'publicly_queryable'  => false,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-welcome-learn-more',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'supports'            => [ 'title' ],
		'taxonomies'          => [ 'chapter' ],
		'has_archive'         => false,
		'rewrite'             => [
			'slug' => 'questions',
		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
